name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Install frontend dependencies
      working-directory: ./public/admin-staging
      run: npm install
      
    - name: Build React frontend
      working-directory: ./public/admin-staging
      run: npm run build
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Create deployment package
      run: |
        # Create the deployment directory structure
        mkdir -p deployment
        
        # Copy backend files and package.json
        cp -r backend/* deployment/
        cp package.json deployment/
        cp server.js deployment/
        
        # Copy frontend build files to the correct location
        mkdir -p deployment/public/admin-staging
        cp -r public/admin-staging/dist/* deployment/public/admin-staging/
        
        # Install backend dependencies in deployment directory
        cd deployment
        npm ci --production --silent
        
        # Create the deployment package WITH node_modules
        cd ..
        cd deployment
        zip -r ../complete-deployment.zip . -x "*.log" ".env*" "deploy*.sh" "*.zip"
        
    - name: Deploy complete application to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: homework-helper-staging
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
        package: complete-deployment.zip
          
    - name: Verify deployment
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        echo "Testing backend API..."
        curl -f https://homework-helper-staging.azurewebsites.net/api/health || exit 1
        echo "Testing frontend..."
        curl -f https://homework-helper-staging.azurewebsites.net/public/admin-staging/ || exit 1
        echo "✅ Staging deployment successful!"