name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Deploy to Azure App Service
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'
        inlineScript: |
          # Create deployment package
          cd backend
          zip -r ../deployment.zip . -x "node_modules/*" "*.log" ".env*" "deploy*.sh" "*.zip"
          
          # Deploy to Azure
          az webapp deploy --resource-group homework-helper-stage-rg-f --name homework-helper-staging --src-path ../deployment.zip --type zip
          
          # Restart the app
          az webapp restart --name homework-helper-staging --resource-group homework-helper-stage-rg-f
          
    - name: Verify deployment
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        curl -f https://homework-helper-staging.azurewebsites.net/api/health || exit 1
        echo "✅ Staging deployment successful!"