name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Run tests
      working-directory: ./backend
      run: npm test
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Create deployment package
      run: |
        cd backend
        zip -r ../deployment.zip . -x "*.log" ".env*" "deploy*.sh" "*.zip"
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: homework-helper-prod
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRODUCTION }}
        package: deployment.zip
        
    - name: Verify deployment
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        curl -f https://homework-helper-prod.azurewebsites.net/api/health || exit 1
        echo "✅ Production deployment successful!"
        
    - name: Notify deployment success
      run: |
        echo "🎉 Production deployment completed successfully!"
        echo "🌐 Production URL: https://homework-helper-prod.azurewebsites.net"
        echo "🔧 Admin Portal: https://homework-helper-prod.azurewebsites.net/admin/"